# Docker Offload - Override with Large Model
version: '3.8'

services:
  backend:
    # Override model with a larger model for offload
    models: !override
      qwen3-large:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

# Large model for Docker Offload scenarios  
models:
  qwen3-large:
    model: ai/qwen2.5-coder:14B-Q4_K_M  # 8.5 GB - Good balance of size/performance
    context_size: 15000  # Larger context for complex coding tasks
    runtime_flags:
      - "--threads=8"
      - "--ctx-size=15000"
      - "--batch-size=512"