

services:
  web-app:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_MODE=local
    depends_on:
      - api
    networks:
      - code-assistant

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_SIZE=small
      - USE_GPU=false
      - MODEL_NAME=Salesforce/codet5-small
      - MAX_TOKENS=100
    volumes:
      - model_cache:/app/models
    networks:
      - code-assistant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_cache:
    driver: local

networks:
  code-assistant:
    driver: bridge
